### ISSUE TITLE
Globals aren't highlighted

### ISSUE THREAD

**Issue by rm-code** [nebularg/linter-lua-findglobals#1]
Hello,

![sc](https://cloud.githubusercontent.com/assets/11627131/8521513/a5bd4c20-23e4-11e5-84f9-22c059b285ee.png)
I use the default settings of the plugin.

Best wishes,
Robert

**Comment by nebularg** [comment]
Did you save the file? I noticed that it didn't start linting until it had a path

![2015-07-06_18-40-33](https://cloud.githubusercontent.com/assets/1010803/8535765/9d14d9ba-240e-11e5-87aa-e981f1b3b730.png)

There can also be some weird behavior having multiple tabs open including non-code tabs (find, settings, etc) when switching between them

**Comment by rm-code** [comment]
Thanks for the reply. The file was saved and the only open tab.

I just deactivated all other packages except for language-lua and your linter-lua-findglobals, but to no avail.

Is there anything else I could try, or some other information I could give you?

**Comment by nebularg** [comment]
Guess I should have started with this, but do you have luac on your path/available on your system? I kind of gloss over the fact that I use luac for linting in the readme

**Comment by rm-code** [comment]
Yes, I have `luac` in my PATH I think (`which luac` returns /usr/local/bin/luac). I also use the linter and linter-lua packages and they throw an error when I don't start Atom through the terminal and therefore don't give it access to my PATH.

![screenshot 2015-07-07 09 09 44](https://cloud.githubusercontent.com/assets/11627131/8540692/4f832dda-2488-11e5-8029-8d74a66fe7be.png)

EDIT: 

I deactivated autosaving, because I thought that maybe it wouldn't trigger the linter correctly, but saving manually doesn't work either.

Is there a way I could check if the linter is doing anything? Other than showing up in my installed packages I don't get any reaction from it.
